# Generated by Django 5.0.6 on 2024-09-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revynapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
    ]
