# Generated by Django 5.0.6 on 2024-10-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revynapp', '0002_remove_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=50, unique=True)),
                ('responses', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('intent', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
