# Generated by Django 5.0.6 on 2024-10-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revynapp', '0006_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='file_content',
            field=models.TextField(default='', null=True),
        ),
    ]
